### ISSUE TITLE
Does not work with angular 6

### ISSUE THREAD

**Issue by Antarius225** [tommueller/ng-mat-search-bar#1]
I cannot import your component while using angular 6.1.0
![image](https://user-images.githubusercontent.com/7151943/45430428-99250780-b6a5-11e8-914b-d108e4f4c6b1.png)
:wave:

**Comment by tommueller** [comment]
Hi, haven't had the time to make the update. You are welcome to send a PR, otherwise I will hopefully find some time to look into this next week. Best!

**Comment by tommueller** [comment]
@Antarius225 I just released a version [2.0.0-beta.1](https://www.npmjs.com/package/ng-mat-search-bar/v/2.0.0-beta.1) which should work with Angular 6. Please test and let me know if it works for you! Cheers

**Comment by Antarius225** [comment]
Cheers 🍾

**Comment by tommueller** [comment]
@Antarius225 I understand this as confirmation that this is working for you now? I'll close this then, if you have more problems reopen this issue.

Cheers
