### ISSUE TITLE
Overly specific peer dependencies after upgrade to 3.1.1

### ISSUE THREAD

**Issue by J12934** [tommueller/ng-mat-search-bar#11]
Hi 👋
Our version was just updated to `3.1.1` and now our build is failing due to some unresolved peer dependencies.

```
npm WARN ng-mat-search-bar@3.1.0 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN ng-mat-search-bar@3.1.0 requires a peer of typescript@~3.1.6 but none is installed. You must install peer dependencies yourself.
```

We use newer versions of both core-js and typescript. Heres our package.json: https://github.com/bkimminich/juice-shop/blob/gsoc2019/frontend/package.json

Is it possible to extend the version range?

For now we are pinning the version to `3.1.0`

Thank you very much 😉

**Comment by tommueller** [comment]
Hi @J12934 ,
sorry for the inconvenience. I reworked the peerDeps completely (they were massively overloaded). I hope this fixes your issues! Version 3.1.2 has just been released.

Cheers,
Tom

**Comment by J12934** [comment]
Wow that was fast! 👍
Works perfectly now. Thank you very much 👌

**Comment by tommueller** [comment]
Sweet. Thanks for reporting the issue!
