### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by Kenji94** [tommueller/ng-mat-search-bar#12]
Hi,
Thanks for your lib!
I spend a few hours to try to implement an autocomplete but did not succeed.
Do you have a way please ?

**Comment by tommueller** [comment]
Hi @Kenji94,
sorry I do not have any time currently to look into this. I have not used autocomplete with ng-mat-search-bar so far, so I cannot assist you.
I am happy to review a pull request if you do implement something, that's all I can offer for now, sorry.

Cheers,
Tom

**Comment by tommueller** [comment]
Closing this, as I cannot offer development of this feature right now and TO did not follow up on this.
