### ISSUE TITLE
Add the "searchVisible" parameter to README

### ISSUE THREAD

**Issue by antoinedelia** [tommueller/ng-mat-search-bar#13]
There is a parameter called `searchVisible` which indicates whether the search bar is opened or closed.

I think this information is quite useful, however it is not described in the README of the project.

Could you please add it so that it helps future developers? 

Thanks a lot!

**Comment by tommueller** [comment]
Hi @antoinedelia,
so far `searchVisible` is only used internally to hide/show elements and trigger some animations. Did not think about people wanting to use it directly (as I suppose consuming the `onOpen` and `onClose` events would be the more common approach). Anyhow I will add the hint to the README.
Cheers,
Tom
