### ISSUE TITLE
Upgrade to Angular 7 & 8

### ISSUE THREAD

**Issue by thejeff77** [tommueller/ng-mat-search-bar#18]
Doesn't seem to find the selector in Angular 8

**Comment by tommueller** [comment]
I have just released a 4.0.0-beta.1 version, which is available on npm. Please test and let me now if it works for you @thejeff77 
Cheers

**Comment by tommueller** [comment]
As there have been no comments otherwise, I assume that it works fine for everyone ...
Will release v4.0.0 later today.

**Comment by thejeff77** [comment]
@trevlewis This may be something you can try on the project now.
