### ISSUE TITLE
FormControl not working

### ISSUE THREAD

**Issue by meghansh36** [tommueller/ng-mat-search-bar#19]
I am passing the control via the the [formControl] input, however, i am not able to access the value of the search text entered.

**Comment by tommueller** [comment]
Dear @meghansh36,
can you provide a stackblitz to illustrate the issue?
Thanks

**Comment by meghansh36** [comment]
Hey,
I got it to work now. Earlier I was using **registerOnChange** but shifting to **valuesChanges** worked like a charm.

**Comment by tommueller** [comment]
Great, closing this then.
