### ISSUE TITLE
Search Icon is not coming instead text "Search is coming"

### ISSUE THREAD

**Issue by sumitsitesh** [tommueller/ng-mat-search-bar#2]
![seachicongithub](https://user-images.githubusercontent.com/23735968/45948911-78e73800-c017-11e8-8eaa-efad3508bcc9.png)
![seachicongithubclose](https://user-images.githubusercontent.com/23735968/45948919-7c7abf00-c017-11e8-8603-63dc51288468.png)

**Comment by tommueller** [comment]
please add Material Icons webfont to your index.html

`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`

as it is described in the [installation guide](https://github.com/tommueller/ng-mat-search-bar#installation)

**Comment by tommueller** [comment]
@sumitsitesh As I did not get any further response from you, I will close this issue. If you have further issues, let me know.
