### ISSUE TITLE
[FEATURE] Custom placeholder text

### ISSUE THREAD

**Issue by vishnu-dev** [tommueller/ng-mat-search-bar#20]
Custom placeholder as input should be a feature @tommueller

**Comment by tommueller** [comment]
@vishnu-dev good idea. I would encourage you to provide a PR, otherwise it might take some time.
Cheers

**Comment by Kogam22** [comment]
@vishnu-dev Can you describe how to call the close() and open() functions. Any help would be appreciated.

**Comment by tommueller** [comment]
@vishnu-dev just added that feature, please test version 4.1.0.
you can just use `[placeholder]="'whatever string'"`
Cheers

**Comment by vishnu-dev** [comment]
Closing as solved.
