### ISSUE TITLE
Subscribe to onEnter event

### ISSUE THREAD

**Issue by 1ycx** [tommueller/ng-mat-search-bar#21]
Can you give a concise example on how to subscribe to the onEnter event ? 
Also, it'd be better if you linked the npm package to github repo so that others know where to create issue or propose PRs. Thanks.

**Comment by 1ycx** [comment]
I figured out how to handle the onEnter event from [here](https://dzone.com/articles/understanding-output-and-eventemitter-in-angular). But what I didn't understand is how to call the `close()` and `open()` functions. Any help with that would be appreciated.

**Comment by 1ycx** [comment]
I finally solved this problem.

**Comment by tommueller** [comment]
@Kogam22 just fyi I linked the repo now to npm. Cheers
