### ISSUE TITLE
Reset the value of search bar after onEnter

### ISSUE THREAD

**Issue by 1ycx** [tommueller/ng-mat-search-bar#22]
```javascript
<mat-search-bar [formControl]="control" 
    (onEnter)="handleSearch($event); search.value = ''; search.close()" 
    #search>
</mat-search-bar>
```
`#localReference.value = ""` does not reset the value. Any help ?

**Comment by tommueller** [comment]
Dear @Kogam22,

first of all: please use platforms like stackoverflow for questions of usage. Issues here reserved for bugs / feature requests etc. pp.

As for your question, I cannot replicate your issue: https://stackblitz.com/edit/angular-7lp5nq

I will close this, if there are still problems with this for you, please use a suitable platform.

Thank you!
