### ISSUE TITLE
Search on iOS not working

### ISSUE THREAD

**Issue by quedicesebas** [tommueller/ng-mat-search-bar#24]
In apple mobile devices the enter actions is not working

**Comment by quedicesebas** [comment]
As this issue of Angular suggested, https://github.com/angular/angular/issues/32963#issuecomment-543712884, the problem is and iOS bug, because of the autocapitalization. I made a PR with the fix as is suggested in that issue comment.

See Pull Request #25

**Comment by tommueller** [comment]
@sebrojas14 Thanks, PR has been merged and released in v4.1.1.
Let me know if it works for, then I can close this issue here.
Cheers

**Comment by tommueller** [comment]
I'll assume this is working now and will close this.
