### ISSUE TITLE
incremental search feature?

### ISSUE THREAD

**Issue by bfredo123** [tommueller/ng-mat-search-bar#26]
Hi,
Thanks for this great component. I would like to use it for incremental search, i.e. with a mat-autocomplete mechanism that would allow me to list found items each time a new letter is typed in  or deleted. Do you have any plans for that? Or how could I do starting on ng-mat-search-bar?

Many thanks!

**Comment by tommueller** [comment]
@bfredo123 I just released version 4.1.3 with autocomplete support. You can just use `<mat-search-bar>` as the `<input>` following the examples on the Angular Material docs for the autocomplete and it should work! https://material.angular.io/components/autocomplete/overview
Let me know if it works for you!
