### ISSUE TITLE
Incompatible peer dependencies found.

### ISSUE THREAD

**Issue by brianpooe** [tommueller/ng-mat-search-bar#27]
Angular v9 project error.

Doing ng update @angular/material I get an error below:

Package "ng-mat-search-bar" has an incompatible peer dependency to "@angular/material" (requires "^8.0.0", would install "9.0.0").

**Comment by tommueller** [comment]
Hi, yes sorry I did not have the time to upgrade the package to Angular 9 so far.
I am not aware of any breaking changes, so probably it should be enough to just extend the peer dependency to also allow for Angular 9.
Could you maybe check that and open a PR?

**Comment by brianpooe** [comment]
Cool will do so.

**Comment by tommueller** [comment]
Merged the PR and released as v9.0.0-beta.0 to be in line with Angular versions from now on.
Please let me know if everything works as expected.

**Comment by brianpooe** [comment]
Works perfect. Thanks.

**Comment by tommueller** [comment]
Resolved in #28
