### ISSUE TITLE
How to access Public methods and properties

### ISSUE THREAD

**Issue by sam3365** [tommueller/ng-mat-search-bar#34]
Can you provide coding examples how to: 

1) Subscribe to the different events (onBlur, onClose, onEnter, onFocus, onOpen)
2) Access the open() and close() public methods from within component typescript code
3) Accessing the searchVisible property.

Thank you.

**Comment by tommueller** [comment]
Hi @steve1mercury 
This is really basic Angular functionality, so I will not get into details. Some hints:
1. the events can be subscribed to from template, i.e.:
```
<mat-search-bar (onBlur)="yourOnBlurFunction($event)"></mat-search-bar>
```
2. you will need to get the component instance in the ts code. Usually this will be done using the `@ViewChild`-decorator:
```ts
@ViewChild(MatSearchBar) matSearchBar;

...

yourFunction() {
  if (this.matSearchBar.searchVisible) doSomething();
  else this.matSearchBar.open();
}
```

Hope this helps!
