### ISSUE TITLE
Error when import in lazy loaded module in Angular 7

### ISSUE THREAD

**Issue by dodongphure** [tommueller/ng-mat-search-bar#4]
When I imported `NgMatSearchBarModule` in my lazy loaded module, it show error: 

> BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

Because in app.module.ts I already imported `BrowserAnimationsModule`, so I think should change the import in `NgMatSearchBarModule`, replace `BrowserAnimationsModule` with `CommonModule`.

**Comment by tommueller** [comment]
Thanks for reporting this issue! However I cannot reproduce it. Can you create a plunkr or stackblitz to demonstrate the issue? Cheers!

**Comment by dodongphure** [comment]
Hi @tommueller, here is the codes sample https://stackblitz.com/edit/angular-znywpe

**Comment by Rehan1579** [comment]
Hi, i'm also facing the same issue....

**Comment by denisenricohasyim93** [comment]
same here ...

**Comment by tommueller** [comment]
Sorry I have been on vacation this week.
Thanks for the blitz @dodongphure, I will look into it this week!

**Comment by tommueller** [comment]
Hi, should be fixed in v3.1.0 release, refer to this edited stackblitz where it is working now: https://stackblitz.com/edit/angular-uhu9tw
