### ISSUE TITLE
Remove white background

### ISSUE THREAD

**Issue by BastienFerbu** [tommueller/ng-mat-search-bar#5]
Hi,
When I put `mat-search-bar` in my blue `mat-toolbar`, the  background is white so I can't see anything. I tried to remove it with a css (`background: transparent;` or `background-color: transparent;`) but it's still present...
Only when I remove it directly in the browser it work, but I can't see the icons... 
I don't know if it's an issue or just me don't know how to use the module, I'm a beginner in Angular.

**Comment by tommueller** [comment]
Hi @BastienFerbu 
Thanks for reporting the issue. I will look into it this week and let you!
Cheers

**Comment by tommueller** [comment]
Hi, should be fixed in v3.1.0 release. Let me know if there are any issues!

**Comment by BastienFerbu** [comment]
It works perfectly! Thank you !
